"""add folder column to pads

Revision ID: 78e9e486c306
Revises: df7edf54b56b
Create Date: 2026-07-05 18:40:42.126970
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '78e9e486c306'
down_revision: Union[str, None] = 'df7edf54b56b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pads', sa.Column('folder', sa.String(length=80), nullable=True), schema='pad_ws')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pads', 'folder', schema='pad_ws')
    # ### end Alembic commands ###
