"""reconcile index names and tags column type

Revision ID: df7edf54b56b
Revises: 5396c6b1f129
Create Date: 2026-07-05 18:33:56.020808
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'df7edf54b56b'
down_revision: Union[str, None] = '5396c6b1f129'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_pad_versions_pad_id'), table_name='pad_versions', schema='pad_ws')
    op.create_index(op.f('ix_pad_ws_pad_versions_pad_id'), 'pad_versions', ['pad_id'], unique=False, schema='pad_ws')
    op.alter_column('pads', 'tags',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.ARRAY(sa.String(length=50)),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"),
               schema='pad_ws')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pads', 'tags',
               existing_type=sa.ARRAY(sa.String(length=50)),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"),
               schema='pad_ws')
    op.drop_index(op.f('ix_pad_ws_pad_versions_pad_id'), table_name='pad_versions', schema='pad_ws')
    op.create_index(op.f('idx_pad_versions_pad_id'), 'pad_versions', ['pad_id', sa.literal_column('created_at DESC')], unique=False, schema='pad_ws')
    # ### end Alembic commands ###
